# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - bestocr

on:
  push:
    branches:
      - feature-containerize-app
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://projectocrregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ce80ba3529c545469deed34df4c76c0c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_280c125e593740ccb9bfb869d7bf3880 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: projectocrregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ce80ba3529c545469deed34df4c76c0c }}/projectocrregistry/fastapi_ocr:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bestocr'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6e580bb7766e44619d05e026362d1f40 }}
        images: 'projectocrregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ce80ba3529c545469deed34df4c76c0c }}/projectocrregistry/fastapi_ocr:${{ github.sha }}'